databases:
  - name: kiruthik
databaseName: kiruthik
user: kiruthik_user

services:
  - type: web
name: kiruthik
env: ruby
buildCommand: "./bin/render-build.sh"
startCommand: "bundle exec puma -C config/puma.rb"
envVars:
  - key: DATABASE_URL
fromDatabase:
name: kiruthik
property: connectionString
  - key: RAILS_MASTER_KEY
sync: false